# -*- coding: utf-8 -*-
"""Week_4_Logistics_Predictive_Modeling

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dLr8nBHsJJye4AkgQzPKiB5mX2XWWL5s
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

np.random.seed(42)

print("Libraries imported successfully!")

n = 1000

df = pd.DataFrame({
    "shipment_id": [f"SHP{i:05d}" for i in range(1, n + 1)],
    "shipment_date": pd.date_range("2025-01-01", periods=n, freq="D"),
    "transport_mode": np.random.choice(
        ["Road", "Rail", "Air", "Sea"],
        n,
        p=[0.50, 0.20, 0.15, 0.15]
    ),
    "region": np.random.choice(
        ["North", "South", "East", "West", "Central"],
        n
    )
})

df["distance_km"] = np.clip(
    np.random.gamma(3, 250, n),
    50,
    2000
)

df["shipment_volume"] = np.clip(
    np.random.gamma(4, 20, n),
    5,
    250
)

cost_per_km = df["transport_mode"].map({
    "Road": 1.8,
    "Rail": 1.2,
    "Air": 4.5,
    "Sea": 0.9
})

df["transportation_cost"] = np.maximum(
    100,
    df["distance_km"] * cost_per_km
    + df["shipment_volume"] * 8
    + np.random.normal(0, 150, n)
)

df["fuel_cost"] = np.maximum(
    20,
    df["distance_km"] * np.random.uniform(0.18, 0.35, n)
)

base_time = df["transport_mode"].map({
    "Road": 2.5,
    "Rail": 4.5,
    "Air": 1.2,
    "Sea": 7.0
})

df["delivery_time_days"] = np.maximum(
    0.5,
    base_time
    + df["distance_km"] / 350
    + df["shipment_volume"] / 180
    + np.random.normal(0, 1.5, n)
)

df["delay_days"] = np.maximum(
    -2,
    np.random.normal(0.5, 2.5, n)
)

df["delivery_status"] = np.where(
    df["delay_days"] > 0,
    "Delayed",
    "On-Time"
)

print("Dataset created successfully!")
print("Dataset shape:", df.shape)

df.head()

print("Dataset Information:")
print(df.info())

print("\nDataset Shape:")
print(df.shape)

print("\nMissing Values:")
print(df.isnull().sum())

print("Descriptive Statistics:")
numeric_data = df.select_dtypes(include=np.number)
display(numeric_data.describe().round(2))

print("Average Delivery Time:", round(df["delivery_time_days"].mean(), 2), "days")
print("Average Shipment Volume:", round(df["shipment_volume"].mean(), 2))
print("Average Transportation Cost:", round(df["transportation_cost"].mean(), 2))
print("Average Distance:", round(df["distance_km"].mean(), 2), "km")
print("Average Fuel Cost:", round(df["fuel_cost"].mean(), 2))

plt.figure(figsize=(8, 5))
plt.hist(df["delivery_time_days"], bins=30)
plt.title("Distribution of Delivery Time")
plt.xlabel("Delivery Time (Days)")
plt.ylabel("Number of Shipments")
plt.tight_layout()
plt.show()

mode_avg = df.groupby("transport_mode")["delivery_time_days"].mean().sort_values()

plt.figure(figsize=(8, 5))
mode_avg.plot(kind="bar")
plt.title("Average Delivery Time by Transport Mode")
plt.xlabel("Transport Mode")
plt.ylabel("Average Delivery Time (Days)")
plt.xticks(rotation=0)
plt.tight_layout()
plt.show()

print(mode_avg.round(2))

plt.figure(figsize=(8, 5))

plt.scatter(
    df["distance_km"],
    df["delivery_time_days"],
    alpha=0.6
)

plt.title("Distance vs. Delivery Time")
plt.xlabel("Distance (km)")
plt.ylabel("Delivery Time (Days)")
plt.tight_layout()
plt.show()

target = "delivery_time_days"

features = [
    "shipment_volume",
    "transportation_cost",
    "distance_km",
    "fuel_cost",
    "transport_mode",
    "region"
]

X = df[features]
y = df[target]

categorical_features = ["transport_mode", "region"]
numeric_features = [
    "shipment_volume",
    "transportation_cost",
    "distance_km",
    "fuel_cost"
]

print("Target variable:", target)
print("Features:", features)

preprocessor = ColumnTransformer([
    ("cat", OneHotEncoder(handle_unknown="ignore"), categorical_features),
    ("num", "passthrough", numeric_features)
])

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.20, random_state=42
)

print("Training records:", len(X_train))
print("Testing records:", len(X_test))

linear_model = Pipeline([
    ("preprocessor", preprocessor),
    ("model", LinearRegression())
])

linear_model.fit(X_train, y_train)

linear_pred = linear_model.predict(X_test)

linear_mae = mean_absolute_error(y_test, linear_pred)
linear_rmse = np.sqrt(mean_squared_error(y_test, linear_pred))
linear_r2 = r2_score(y_test, linear_pred)

print("Linear Regression Results")
print("-------------------------")
print("MAE :", round(linear_mae, 4))
print("RMSE:", round(linear_rmse, 4))
print("R²  :", round(linear_r2, 4))

rf_model = Pipeline([
    ("preprocessor", preprocessor),
    ("model", RandomForestRegressor(
        n_estimators=200,
        max_depth=12,
        min_samples_split=4,
        random_state=42,
        n_jobs=-1
    ))
])

rf_model.fit(X_train, y_train)

rf_pred = rf_model.predict(X_test)

rf_mae = mean_absolute_error(y_test, rf_pred)
rf_rmse = np.sqrt(mean_squared_error(y_test, rf_pred))
rf_r2 = r2_score(y_test, rf_pred)

print("Random Forest Results")
print("---------------------")
print("MAE :", round(rf_mae, 4))
print("RMSE:", round(rf_rmse, 4))
print("R²  :", round(rf_r2, 4))

results = pd.DataFrame({
    "Model": ["Linear Regression", "Random Forest"],
    "MAE": [linear_mae, rf_mae],
    "RMSE": [linear_rmse, rf_rmse],
    "R2": [linear_r2, rf_r2]
})

display(results.round(4))

cv_scores = cross_val_score(
    linear_model,
    X,
    y,
    cv=5,
    scoring="neg_root_mean_squared_error"
)

cv_rmse = -cv_scores

print("Linear Regression 5-Fold Cross-Validation")

for i, score in enumerate(cv_rmse, start=1):
    print(f"Fold {i} RMSE: {score:.4f}")

print("\nMean CV RMSE:", round(cv_rmse.mean(), 4))

plt.figure(figsize=(7, 5))

plt.scatter(
    y_test,
    linear_pred,
    alpha=0.6
)

plt.xlabel("Actual Delivery Time (Days)")
plt.ylabel("Predicted Delivery Time (Days)")
plt.title("Actual vs. Predicted Delivery Time - Linear Regression")

plt.tight_layout()
plt.show()

mode_summary = df.groupby("transport_mode").agg(
    Average_Delivery_Time=("delivery_time_days", "mean"),
    Average_Transportation_Cost=("transportation_cost", "mean"),
    Average_Fuel_Cost=("fuel_cost", "mean")
).sort_values("Average_Delivery_Time")

print("Transport Mode Optimization Analysis")
print("------------------------------------")
display(mode_summary.round(2))

correlation = df[
    [
        "delivery_time_days",
        "shipment_volume",
        "transportation_cost",
        "distance_km",
        "fuel_cost",
        "delay_days"
    ]
].corr()["delivery_time_days"].sort_values(ascending=False)

print("Correlation with Delivery Time")
print("------------------------------")
print(correlation.round(3))

df.to_csv("Week_4_Logistics_Synthetic_Dataset.csv", index=False)

results.to_csv(
    "Week_4_Model_Comparison.csv",
    index=False
)

mode_summary.to_csv(
    "Week_4_Transport_Mode_Summary.csv"
)

print("Files saved successfully!")
print("1. Week_4_Logistics_Synthetic_Dataset.csv")
print("2. Week_4_Model_Comparison.csv")
print("3. Week_4_Transport_Mode_Summary.csv")